# Generated by Django 4.2.30 on 2026-04-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-data_compra'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-data_evento'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='ingresso',
            options={'ordering': ['evento__data_evento', 'tipo'], 'verbose_name': 'Ingresso', 'verbose_name_plural': 'Ingressos'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['nome'], 'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterField(
            model_name='local',
            name='capacidade',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='local',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
