sonar.projectKey=sounicolaslima_eventos-universitarios
sonar.organization=eventos-universitarios

sonar.sources=src
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=src/**/migrations/**,src/**/tests.py,src/eventos/tasks.py,src/eventos_universitarios/asgi.py,src/eventos_universitarios/wsgi.py,src/eventos_universitarios/models.py

sonar.sourceEncoding=UTF-8
sonar.exclusions=src/staticfiles/**