# Generated by Django 6.0.5 on 2026-05-12 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_categoria_options_alter_compra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='codigo_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
